services:
  agate:
    build: agate
    ports:
      - 1970:1965
    networks:
      geminet:

  gegobi:
    build: gegobi
    ports:
      - 1972:1965
    networks:
      geminet:

  gemigit:
    build: gemigit
    ports:
      - 1965:1965
    networks:
      geminet:

  jags-php:
    build: jags-php
    ports:
      - 1969:1965
    networks:
      geminet:

  lupa-pona:
    build: lupa-pona
    ports:
      - 1968:1965
    networks:
      geminet:

  molly-brown:
    build: molly-brown
    ports:
      - 1966:1965
    networks:
      geminet:

  orion:
    build: orion
    ports:
      - 1967:1965
    networks:
      geminet:

  titan2:
    build: titan2
    ports:
      - 1971:1965
    networks:
      geminet:

networks:
  geminet:
