services:
  gemigit:
    build: gemigit
    ports:
      - 1965:1965
    networks:
      geminet:

  molly-brown:
    build: molly-brown
    ports:
      - 1966:1965
    networks:
      geminet:

  orion:
    build: orion
    ports:
      - 1967:1965
    networks:
      geminet:

networks:
  geminet:
